# How are numpy arrays stored?

In [1]:
import numpy as np

Numpy presents an n-dimensional abstraction that has to be fit into 1-dimensional computer memory.

Even for 2 dimensions (matrices), this leads to confusion: row-major, column-major.

In [2]:
A = np.arange(9).reshape(3, 3)
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## Strides and in-memory representation

How is this represented in memory?

In [3]:
A.strides

(24, 8)

* `strides` stores for each axis by how many bytes one needs to jump to get from one entry to the next (in that axis)
* So how is the array above stored?
* This captures row-major ("C" order) and column-major ("Fortran" order), but is actually much more general.

In [10]:
bytes(A.astype(np.uint8))

b'\x00\x01\x02\x03\x04\x05\x06\x07\x08'

We can also ask for Fortran order:

In [11]:
A2 = np.arange(9).reshape(3, 3, order="F")
A2

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

`numpy` defaults to row-major order.

In [12]:
A2.strides

(8, 24)

In [13]:
bytes(A2.astype(np.uint8))

b'\x00\x03\x06\x01\x04\x07\x02\x05\x08'

## Strides and Contiguity

How is the stride model more general than just saying "row major" or "column major"?

In [14]:
A = np.arange(16).reshape(4, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
A.strides

(32, 8)

In [16]:
Asub = A[:3, :3]
Asub

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

Recall that `Asub` constitutes a *view* of the original data in `A`.

In [17]:
Asub.strides

(32, 8)

Now `Asub` is no longer a *contiguous* array!

From the linear-memory representation (as show by the increasing numbers in `A`) 3, 7, 11 are missing.

This is easy to check by a flag:

In [18]:
Asub.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False